name = "cursed"
description = "Very nice amirite"
# Gleam won't let me put my own license :(
# licences = ["The Shit Software License"]
repository = { type = "github", user = "isaacharrisholt", repo = "cursed-gleam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
